language: python

python:
  - "3.7"

matrix:
  fast_finish: true

sudo: required
dist: bionic

env:
  # This variable is required for Qt to work on CI.
  - QT_QPA_PLATFORM="offscreen"

install:
  # install dependencies.
  pip install --upgrade pip setuptools wheel
  pip install -e .

script:
  - pytest