language: python

python:
  - "3.7"

jobs:
  fast_finish: true

env:
  # This variable is required for QTest to work on Travis CI.
  - QT_QPA_PLATFORM="offscreen"

install:
  # install dependencies.
  - pip install --upgrade pip setuptools wheel
  - pip install -e .

script:
  - pytest